import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/Components/ClientLayout";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VirtualDoc",
  description: "Generated by create next app",
  icons: {
    icon: "/Assets/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div ><ClientLayout>{children}</ClientLayout></div>
      </body>
    </html>
  );
}
